name: Builder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.x'
    - run: |
        chmod +x ./gradlew
        ./gradlew :lib:assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: module_release
        path: lib/build/module/magisk_module_release/