name: Builder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - run: |
        chmod +x ./gradlew
        ./gradlew :lib:assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: module_release
        path: /lib/build/module/magisk_module_release/