name: Debug
on:
  push:
    branches:
      - dev
      - test
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.x'
    - run: |
        chmod +x ./gradlew
        ./gradlew :lib:assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: module_debug
        path: lib/build/module/magisk_module_debug/